export default [
  {
    id: "1",
    title: "Polos",
    price: 16,
    offerPrice: null,
    stock: 12,
    img: "apples.jpg",
    category: "fruits",
  },
  {
    id: "2",
    title: "Sudadera",
    price: 39.99,
    offerPrice: 34.99,
    stock: 12,
    img: "baby.jpg",
    category: "vegetable",
  },
  {
    id: "3",
    title: "abciquam feugiat beans",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "beans.jpg",
    category: "vegetable",
  },
  {
    id: "4",
    title: "Lorem am beans dui non",
    price: 1.88,
    offerPrice: null,
    stock: 12,
    img: "beans2.jpg",
    category: "vegetable",
  },
  {
    id: "5",
    title: "Berry es feugiat mollis",
    price: 2.3,
    offerPrice: null,
    stock: 12,
    img: "berry.jpg",
    category: "fruits",
  },
  {
    id: "6",
    title: "berry feugiat dui non mollis",
    price: 2.22,
    offerPrice: null,
    stock: 12,
    img: "berry2.jpg",
    category: "fruits",
  },
  {
    id: "7",
    title: "brussels feugiat dui non mollis",
    price: 2.88,
    offerPrice: null,
    stock: 12,
    img: "brussels.jpg",
    category: "vegetable",
  },
  {
    id: "8",
    title: "carrot feugiat dui non mollis",
    price: 3.88,
    offerPrice: null,
    stock: 12,
    img: "carrot.jpg",
    category: "vegetable",
  },
  {
    id: "9",
    title: "celery feugiat dui non mollis",
    price: 5.88,
    offerPrice: null,
    stock: 12,
    img: "celery.jpg",
    category: "vegetable",
  },
  {
    id: "11",
    title: "cherry feugiat dui non mollis",
    price: 7.88,
    offerPrice: 6.88,
    stock: 12,
    img: "cherry.jpg",
    category: "fruits",
  },
  {
    id: "22",
    title: "chicken feugiat dui non mollis",
    price: 4.88,
    offerPrice: null,
    stock: 12,
    img: "chicken.jpg",
    category: "meat",
  },
  {
    id: "33",
    title: "Aliquam feugiat non chicken",
    price: 8.88,
    offerPrice: null,
    stock: 12,
    img: "chicken2.jpg",
    category: "meat",
  },
  {
    id: "44",
    title: "clemen feugiat dui",
    price: 4.99,
    offerPrice: null,
    stock: 12,
    img: "clemen.jpg",
    category: "fruits",
  },
  {
    id: "55",
    title: "cod feugiat dui non",
    price: 9.88,
    offerPrice: null,
    stock: 12,
    img: "cod.jpg",
    category: "meat",
  },
];
